### ISSUE TITLE
Creation of Dynamic Properties Deprecated in PHP 8.2

### ISSUE THREAD

**Issue by ElusiveMind** [backdrop-contrib/xautoload#1]
All properties used in classes must be declared beginning in PHP 8.2. This throws warnings but will be unsupported and error in PHP 9.

Make sure that all classes using $this->variable have the variable declared in scope at the top of the class.

**Comment by VasasA** [comment]
Thank You very much, PR is merged. 👍

**Comment by VasasA** [comment]
Drupal 7 X Autoload module's maintainer uses the 'protected' visibility for the properties: [commit](https://git.drupalcode.org/project/xautoload/-/commit/ce47eb2da3dd3c5015611742fed14103448ec0c2)
I follow this in a [new commit](https://github.com/backdrop-contrib/xautoload/commit/f6f43c7474ea280adf144f5ebc7d1dc8b6bb51cb).
